version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: akshayhere/teachers-portal-app:latest
    container_name: teachers-portal-app
    restart: on-failure:5 # Try to restart 5 times on failure then stops.
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/src/index.js"

  db:
    image: mysql:8.0
    container_name: teachers-portal-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
