FROM node:18-alpine

WORKDIR /app

# Install all dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
ENV NODE_ENV=development
ENV PORT=3000
EXPOSE 3000

# Use ts-node-dev for hot reload
# CMD ["sh", "-c", "npx prisma generate && npx prisma migrate dev && npm run dev"]
