version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: teachers-portal-app
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - .:/app                
      - node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev && npm run dev"

  db:
    image: mysql:8.0
    container_name: teachers-portal-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  node_modules:
