## Reference: https://medium.com/@brbabic/how-to-send-http-request-from-visual-studio-code-e70d9b2ea591

@teacher = tir@nizumwup.my
@student1 = recuzli@lew.gp
@student2 = bruce-banner@gmail.com

###
GET http://localhost:3000/api/teachers
Content-Type: application/json
###

POST http://localhost:3000/api/teachers/register
Content-Type: application/json

{
  "teacher": "{{teacher}}",
  "students": ["{{student1}}"]
}

###
GET http://localhost:3000/api/commonstudents?teacher=tir%40nizumwup.my&teacher=odin%40gmail.com
Content-Type: application/json
###

POST http://localhost:3000/api/suspend
Content-Type: application/json

{
  "student": "{{student1}}"
}

###

###

POST http://localhost:3000/api/retrievefornotifications
Content-Type: application/json

{
  "teacher":  "{{teacher}}",
  "notification": "Hello students! @loki@gmail.com @bruce-banner@gmail.com @loki@gmail.com"
}

###